[toolchain]
channel = "1.91.1"
profile = "minimal"
components = [ "rustfmt", "clippy" ]
targets = [
    "wasm32-wasip2", # extensions
    "wasm32-unknown-unknown", # web
    "x86_64-unknown-linux-musl", # remote server
]
